#Development notes

Want to make 'superman' a bit more user friendly. this means stripping out ALL hardcoding and allowing switching on and off of advanced features like rotation

In [10]:
%load_ext autoreload
%autoreload 1
%aimport model3d
%aimport vel_prism

m3d = model3d
vp = vel_prism


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


So what does the model actually need, what is unnecesary?

In [11]:
import os
import pickle
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
import matplotlib.pyplot as plt

time = []

wvl = [4000,6000,8000]
spectra = [100,200,300]
spectra_errors = [2,2,2]

time = [54341.056842]*10

wvl = np.array(wvl)
spectra = np.array(spectra)
spectra_errors = np.array(spectra_errors)
time = np.array(time)

sodium_d = [5889.950,5895.924]
midtransit = 54341.056842
period =  2.21857312
planet_K = 154
planet_K = 0
star_K = 0.20196
line_centers = sodium_d
plotting = True
nproc = 4
save_star = False

star_flux = np.array([1000,1000,1000])

star_profile = {'wvl':wvl,'spectrum':star_flux}

planet_absorb = np.array([1.0,1.0,1.0])

spot_profile = np.array([500,1000,1000])/2.0

spotlong, spotlat, spotsize, spotfilling_factor = 0, 45, 20, 1.0

spotlong2, spotlat2, spotsize2, spotfilling_factor2 = 0, 90, 20, 0.1


In [12]:
x1 = [0.51374991, 0.18869174, 8.5049162065200008, -0.15442891679199999,  0.23553298503299999, 0.063145416345300007, -3.50757872893e+50, 111.002838225,spotlong,spotlat,spotsize,spotfilling_factor,spotlong2,spotlat2,spotsize2,spotfilling_factor2]

In [13]:
spotlong = []
spotlat = []
spotsize = []
spotfill = []
for i in range(0,len(x1[8:])/4):
    spotlong +=[x1[i*4 + 8]]
    spotlat +=[x1[i*4 + 9]]
    spotsize +=[x1[i*4 + 10]]
    spotfill +=[x1[i*4 + 11]]


In [18]:
p0 = 0.1572
system_scale = 1.0/8.92
gamma_0 = x1[0]
gamma_1 = x1[1]
inc = 85.68
east_offset = x1[2]*0
west_offset = x1[3]*0
atm_radius = x1[4]
star_vsini = 0
load_star = False
location= 'full'
absolute = 'false'

input = [p0,system_scale,gamma_0,gamma_1,inc,star_vsini,planet_K,star_K,midtransit,period,east_offset,west_offset,atm_radius]
data_x = (time-midtransit)/period
spot_data = True

full_model = vp.vel_prism(data_x, input, star_profile, time,planet_absorb,spot_data=spot_data, type_data='FLUX',plotting=plotting,nproc=nproc,save_star=save_star,load_star=load_star,location=location,absolute=absolute,spot_profile=spot_profile,spotlong=spotlong,spotlat=spotlat,spotsize=spotsize,spotfill=spotfill)

[ 0.99291626  0.98620795  0.98620795]

In [19]:
print full_model

[[ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]
 [ 0.99291626  0.98620795  0.98620795]]


WARNING!!! Initial tests show that our redshifting program produces unreliable results for low binsizes. this does of course make sense, sinse it needs many bins to interpolate and I only give it 3. add a condition that it doesn't try to do this if velocity is set to 0