#Development notes

Want to make 'superman' a bit more user friendly. this means stripping out ALL hardcoding and allowing switching on and off of advanced features like rotation

In [1]:
%load_ext autoreload
%autoreload 1
%aimport model3d
m3d = model3d

So what does the model actually need, what is unnecesary?

In [10]:
import os
import pickle
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
import matplotlib.pyplot as plt

sodium_d = [5889.950,5895.924]

time = []

wvl = [4000,6000,8000]
spectra = [100,200,300]
spectra_errors = [2,2,2]

time = [54341.056842]*1000

wvl = np.array(wvl)
spectra = np.array(spectra)
spectra_errors = np.array(spectra_errors)
time = np.array(time)

planet_K = 154
sodium_d = [5889.950,5895.924]
midtransit = 54341.056842
period =  2.21857312
planet_K = 154
planet_K = 0
star_K = 0.20196
line_centers = sodium_d
plotting = False
nproc = 4
best_fit=False
save_star = False

load = True
save = True
save_m1 = 'test1.p'
save_m2 = 'test2.p'

star_flux = np.array([1000,1000,1000])

star_profile = {'wvl':wvl,'spectrum':star_flux}

planet_absorb = np.array([1.0,1.0,1.0])

spot_profile = np.array([500,1000,1000])/2.0

spotlong, spotlat, spotsize, spotfilling_factor = 0, 45, 20, 0

spotlong2, spotlat2, spotsize2, spotfilling_factor2 = 0, 90, 20, 1.0


In [11]:
x1 = [0.51374991, 0.18869174, 8.5049162065200008, -0.15442891679199999,  0.23553298503299999, 0.063145416345300007, -3.50757872893e+50, 111.002838225,spotlong,spotlat,spotsize,spotfilling_factor,spotlong2,spotlat2,spotsize2,spotfilling_factor2]

In [ ]:
full_model = m3d.model_3d(x1,time,period,planet_K,star_K,midtransit,wvl,line_centers,plotting,star_profile,planet_absorb,spot_profile=spot_profile,nproc=nproc,best_fit=best_fit,save_star=save_star,star_vsini=0)

In [9]:
print full_model

[[ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494  0.97176494]
 [ 0.97062137  0.97176494

[ 0.97062137  0.97176494  0.97176494]

WARNING!!! Initial tests show that our redshifting program produces unreliable results for low binsizes. this does of course make sense, sinse it needs many bins to interpolate and I only give it 3. add a condition that it doesn't try to do this if velocity is set to 0